apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -v1
labels:
  - pairs:
      app.kubernetes.io/version: v1
    includeSelectors: true
    includeTemplates: true
configMapGenerator:
  - name: angie-version
    files:
      - version.conf
