apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  namespace: argocd
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values: [argocd-metrics, argocd-server-metrics, argocd-repo-server-metrics]
  endpoints:
    - port: http-metrics
