apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - namespace.yaml
  - overlays/v1
  - overlays/v2
  - httproute.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
