apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: angie
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: angie
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
