terraform {
  required_version = ">= 1.8.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

variable "backend" {
  description = "Name of the provisioning backend (written into the header)."
  type        = string
}

variable "hostname" {
  description = "Inventory hostname of the node."
  type        = string
}

variable "ip" {
  description = "Address Ansible connects to."
  type        = string
}

variable "host_public_key" {
  description = "SSH host public key of the node (OpenSSH format), pinned in a dedicated known_hosts file."
  type        = string
}

variable "ssh_user" {
  description = "Remote user."
  type        = string
  default     = "ubuntu"
}

variable "ssh_private_key_path" {
  description = "Client private key."
  type        = string
}

variable "ssh_bastion" {
  description = "Optional jump host (user@host)."
  type        = string
  default     = null
}

variable "path" {
  description = "Inventory file path. known_hosts is written next to it."
  type        = string
}

locals {
  known_hosts_path = "${dirname(var.path)}/known_hosts"

  private_key = pathexpand(var.ssh_private_key_path)

  # ProxyCommand instead of ProxyJump: the jump hop does not inherit -i, so with
  # ProxyJump it would silently depend on whatever keys the ssh-agent holds.
  ssh_args = join(" ", compact([
    "-o IdentitiesOnly=yes",
    "-o StrictHostKeyChecking=yes",
    "-o UserKnownHostsFile=${abspath(local.known_hosts_path)}",
    var.ssh_bastion == null ? "" : "-o ProxyCommand=\"ssh -i ${local.private_key} -o IdentitiesOnly=yes -W %h:%p ${var.ssh_bastion}\"",
  ]))

  # Single node today; the control_plane/workers split keeps a later multi-node
  # layout an additive change for the Ansible roles.
  inventory = {
    all = {
      children = {
        k8s_cluster = {
          vars = {
            ansible_user                 = var.ssh_user
            ansible_ssh_private_key_file = local.private_key
            ansible_ssh_common_args      = local.ssh_args
          }
          children = {
            control_plane = {
              hosts = {
                (var.hostname) = { ansible_host = var.ip }
              }
            }
            workers = { hosts = {} }
          }
        }
      }
    }
  }
}

resource "local_file" "known_hosts" {
  filename        = local.known_hosts_path
  file_permission = "0644"
  content         = "${var.ip} ${trimspace(var.host_public_key)}\n"
}

resource "local_file" "inventory" {
  filename        = var.path
  file_permission = "0644"
  content         = "# Generated by OpenTofu (${var.backend}). Do not edit: re-run `tofu apply` instead.\n${yamlencode(local.inventory)}"
}

output "path" {
  description = "Absolute path of the generated inventory."
  value       = abspath(local_file.inventory.filename)
}

output "ssh_args" {
  description = "SSH options used by Ansible (also usable with plain ssh)."
  value       = local.ssh_args
}

output "known_hosts_path" {
  description = "Absolute path of the generated known_hosts."
  value       = abspath(local_file.known_hosts.filename)
}
