apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/rancher/local-path-provisioner.git
      targetRevision: v0.0.37
      path: deploy/chart/local-path-provisioner
      helm:
        valueFiles:
          - $values/gitops/platform/local-path-provisioner/values.yaml
    {{- include "apps.valuesSource" . | nindent 4 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  {{- include "apps.syncPolicy" . | nindent 2 }}
